### ISSUE TITLE
在Telegram上的kokedama_bot所使用的域名已过期

### ISSUE THREAD

**Issue by gulut** [ITJesse/kokedama#1]
我想了解下在Telegram部署的 https://t.me/kokedama_bot 机器人是否为本项目的Demo机器人，如果是的话，这个机器人Eh打包下载功能所使用的kokedama.dev域名似乎已经于近期过期。直接访问机器人所提供的打包下载链接提示No Sponsors，似乎解析已变更。导致这个打包下载功能不可用。

**Comment by ITJesse** [comment]
感谢反馈，已更换域名。
